version: '2'
services:
  gpmaster:
     image: 10.0.0.96:5000/database/centos_greenplum:v2
     hostname: master
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=102
     networks:
       - docker_gwbridge
     ports:
       - "20000:2345"
     volumes:
       - /opt/gpmaster/gpdata:/home/gpadmin/gpdata
       - /opt/gpmaster/conf:/home/gpadmin/conf
       - /opt/gpmaster/etc:/etc
     privileged: true
     tty: true
  gpnode1:
     image: 10.0.0.96:5000/database/centos_greenplum:v2
     hostname: sdw1
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks:
       - docker_gwbridge
     ports:
       - "20001:40000"
       - "20002:40001"
       - "20003:43000"
       - "20004:43001"
     volumes:
       - /opt/gpnode1/gpdata:/home/gpadmin/gpdata
       - /opt/gpnode1/etc:/etc
     privileged: true
     tty: true
  gpnode2:
     image: 10.0.0.96:5000/database/centos_greenplum:v2
     hostname: sdw2
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=110
     networks:
       - docker_gwbridge
     ports:
       - "20005:40000"
       - "20006:40001"
       - "20007:43000"
       - "20008:43001"
     volumes:
       - /opt/gpnode2/gpdata:/home/gpadmin/gpdata
       - /opt/gpnode2/etc:/etc

     privileged: true
     tty: true


